#!/bin/bash

service::config_set() {
  config::check_or_set $1 $2 $SERVICE_CONFIG "${@:3}"
}

check() {
  if [ "$DEBUG" = "true" ]; then
    log::info "[DEBUG][service]: $SERVICE_CONFIG"
    cat $SERVICE_CONFIG
  fi

  service::config_set SECRET_KEY text "SECRET_KEY" $(os::random_string 8)
  service::config_set CLIENT_ID text "CLIENT_ID"
  service::config_set CLIENT_SECRET text "CLIENT_SECRET"
  service::config_set REDIRECT_URI text "REDIRECT_URI"
  service::config_set ADMIN_USERNAME text "ADMIN_USERNAME"
}

check $@
