version: '3.7'

services:
  spug:
    restart: always
    image: whatwewant/connect-doreamon:v1
    platform: linux/amd64
    # ports:
    #   - 0.0.0.0:8080:8080
    environment:
      SECRET_KEY: ${SECRET_KEY}
      #
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      REDIRECT_URI: ${REDIRECT_URI}
      #
      FRONTEND: http://spug_frontend:8080
      BACKEND: http://spug.backend:8080
    links:
      - spug_backend:spug.backend

  spug_frontend:
    image: whatwewant/spug-frontend:${SERVICE_SPUG_VERSION}
    restart: always
    platform: linux/amd64
  
  spug_backend:
    image: whatwewant/spug-backend:${SERVICE_SPUG_VERSION}
    restart: always
    platform: linux/amd64
    environment:
      PORT: 8080
      SECRET_KEY: ${SECRET_KEY}
      #
      REDIS_HOST: spug_redis
      REDIS_PASSWORD: ${SECRET_KEY}
      #
      ADMIN_USERNAME: ${ADMIN_USERNAME}
    volumes:
      - ${SERVICE_DATA}/backend:/data

  spug_redis:
    image: redis:5-alpine
    command: redis-server --requirepass ${SECRET_KEY}
    volumes:
      - ${SERVICE_DATA}/redis:/data

networks:
  default:
    external: true
    name: compose-ingress

