version: '3.7'

services:
  spug:
    restart: always
    image: whatwewant/spug:v2.3.17
    ports:
      - 127.0.0.1:${SERVICE_SPUG_PORT}:80
    environment:
      SECRET_KEY: ${SERVICE_SPUG_SECRET_KEY} # docker-compose exec spug generate_secret_key
      REDIS_HOST: spug_redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: e7b60e02-93c1-4a5d-b244-3917d1e943be
    volumes:
      - ${SERVICE_DATA}/db.sqlite3:/spug/spug_api/db.sqlite3
    depends_on:
      - spug_redis

  spug_redis:
    image: redis:5-alpine
    command: redis-server --requirepass e7b60e02-93c1-4a5d-b244-3917d1e943be
    volumes:
      - ${SERVICE_DATA}/redis:/data

networks:
  default:
    external: true
    name: compose-ingress
