version: '3.7'

services:
  spug:
    restart: always
    image: whatwewant/spug:v2.3.17
    ports:
      - 127.0.0.1:${SERVICE_SPUG_PORT}:80
    environment:
      SECRET_KEY: ${SPUG_SECRET_KEY} # docker-compose exec spug generate_secret_key
      # DB_HOST: spug_mysql
      # DB_PORT: 3306
      # DB_USER: spug
      # DB_PASSWORD: 3a3706bc-b6d5-4413-b187-82acbe70ca01
      # DB_NAME: spug
      REDIS_HOST: spug_redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 3a3706bc-b6d5-4413-b187-82acbe70ca01
    volumes:
      - ./data/db.sqlite3:/spug/spug_api/db.sqlite3
    depends_on:
      - spug_redis

  spug_redis:
    image: redis:5-alpine
    command: redis-server --requirepass 3a3706bc-b6d5-4413-b187-82acbe70ca01
    volumes:
      - ./data/redis:/data

networks:
  default:
    external: true
    name: compose-ingress
